### ISSUE TITLE
Channel license? And Zoom package

### ISSUE THREAD

**Issue by podiki** [johnlepikhin/guix-channel#1]
Thanks for the package definitions! I was just working on a Zoom package for Nonguix and managed to find your channel. I have a working package following a different route currently (using the binary-build-system, similar idea of course). I did see some useful stuff in your Zoom package, like creating the desktop file, so I was curious what the license of this channel is and (assuming it is GPL or similar) what credit line you would want in the Nonguix package to use some of what you wrote here.

**Comment by johnlepikhin** [comment]
Thank you for feedback. I added license information to repository.

**Comment by podiki** [comment]
Great! I'm not sure if I'll end up using anything from your zoom package, but if so, what is the credit line you would like? (Typically in Guix it is name and email)

**Comment by johnlepikhin** [comment]
I also added credits to all files. You may just take it from here: https://github.com/johnlepikhin/guix-channel/blob/master/johnlepikhin/packages/zoom.scm#L2

**Comment by podiki** [comment]
Great, thanks.
